name: "Delete Ephemeral Action"
description: "Deletes an ephemeral"
author: "Apollorion"
branding:
  icon: arrow-up
  color: black
inputs:
  product_name:
    description: "Name of the product (ex. consumer-app)"
    required: true
  gh_token:
      description: "GH token that can create ephemerals"
      required: true
  ref:
    description: "ref of the branch to delete"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"